/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package KalkulatorScientific;

/*
    Nama program : KalkulatorClass.java
    Nama : Rosa Andini Ismayanti, Alesha Naila, Achmad Faruq Mahdison
    NPM : 140810240048, 140810240068, 140810240080
    Tanggal buat : 11/11/2025
    Deskripsi : Class Kalkulator
----------------------------------------------------------------- */

public class KalkulatorFrame extends javax.swing.JFrame {
    
    private KalkulatorClass calculator = new KalkulatorClass();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(KalkulatorFrame.class.getName());

    /**
     * Creates new form KalkulatorFrame
     */
    public KalkulatorFrame() {
        initComponents();
        setFocusable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        judulLabel = new javax.swing.JLabel();
        hasilPanel1 = new javax.swing.JPanel();
        expressionField = new javax.swing.JTextField();
        hasilPanel = new javax.swing.JPanel();
        displayTextField = new javax.swing.JTextField();
        bagiButton = new javax.swing.JButton();
        kaliButton = new javax.swing.JButton();
        kurangButton = new javax.swing.JButton();
        tambahButton = new javax.swing.JButton();
        equalButton = new javax.swing.JButton();
        toggleButton = new javax.swing.JButton();
        hapusButton = new javax.swing.JButton();
        sevenButton = new javax.swing.JButton();
        eightButton = new javax.swing.JButton();
        nineButton = new javax.swing.JButton();
        sixButton = new javax.swing.JButton();
        fiveButton = new javax.swing.JButton();
        fourButton = new javax.swing.JButton();
        twoButton = new javax.swing.JButton();
        threeButton = new javax.swing.JButton();
        oneButton = new javax.swing.JButton();
        zeroButton = new javax.swing.JButton();
        desimalButton = new javax.swing.JButton();
        faktorialButton = new javax.swing.JButton();
        expButton = new javax.swing.JButton();
        akarDuaButton = new javax.swing.JButton();
        delButton = new javax.swing.JButton();
        phiButton = new javax.swing.JButton();
        cosButton = new javax.swing.JButton();
        persenButton = new javax.swing.JButton();
        tanButton = new javax.swing.JButton();
        lnButton = new javax.swing.JButton();
        logButton = new javax.swing.JButton();
        squareButton = new javax.swing.JButton();
        reciprocalButton = new javax.swing.JButton();
        powerButton = new javax.swing.JButton();
        tanhButton = new javax.swing.JButton();
        sinhButton = new javax.swing.JButton();
        coshButton = new javax.swing.JButton();
        sinButton = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel1KeyPressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        judulLabel.setBackground(new java.awt.Color(255, 255, 255));
        judulLabel.setFont(new java.awt.Font("JetBrains Mono", 1, 38)); // NOI18N
        judulLabel.setForeground(new java.awt.Color(255, 255, 255));
        judulLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judulLabel.setText("KALKULATOR SCIENTIFIC");
        jPanel1.add(judulLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 500, -1));

        hasilPanel1.setBackground(new java.awt.Color(0, 0, 0));
        hasilPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 6));
        hasilPanel1.setForeground(new java.awt.Color(255, 153, 51));

        expressionField.setEditable(false);
        expressionField.setBackground(new java.awt.Color(0, 0, 0));
        expressionField.setFont(new java.awt.Font("DS-Digital", 0, 28)); // NOI18N
        expressionField.setForeground(new java.awt.Color(255, 153, 51));
        expressionField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        expressionField.setText("0");
        expressionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expressionFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout hasilPanel1Layout = new javax.swing.GroupLayout(hasilPanel1);
        hasilPanel1.setLayout(hasilPanel1Layout);
        hasilPanel1Layout.setHorizontalGroup(
            hasilPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(expressionField)
        );
        hasilPanel1Layout.setVerticalGroup(
            hasilPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hasilPanel1Layout.createSequentialGroup()
                .addComponent(expressionField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(hasilPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 500, 40));

        hasilPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 6));
        hasilPanel.setForeground(new java.awt.Color(255, 153, 51));

        displayTextField.setEditable(false);
        displayTextField.setBackground(new java.awt.Color(255, 255, 255));
        displayTextField.setFont(new java.awt.Font("DS-Digital", 0, 48)); // NOI18N
        displayTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        displayTextField.setText("0");
        displayTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout hasilPanelLayout = new javax.swing.GroupLayout(hasilPanel);
        hasilPanel.setLayout(hasilPanelLayout);
        hasilPanelLayout.setHorizontalGroup(
            hasilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(displayTextField, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        hasilPanelLayout.setVerticalGroup(
            hasilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hasilPanelLayout.createSequentialGroup()
                .addGap(0, 32, Short.MAX_VALUE)
                .addComponent(displayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(hasilPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 500, 90));

        bagiButton.setBackground(new java.awt.Color(255, 153, 51));
        bagiButton.setFont(new java.awt.Font("JetBrains Mono", 0, 36)); // NOI18N
        bagiButton.setText("÷");
        bagiButton.setAlignmentY(0.0F);
        bagiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bagiButtonActionPerformed(evt);
            }
        });
        jPanel1.add(bagiButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 100, 80));

        kaliButton.setBackground(new java.awt.Color(255, 153, 51));
        kaliButton.setFont(new java.awt.Font("JetBrains Mono", 0, 36)); // NOI18N
        kaliButton.setText("×");
        kaliButton.setAlignmentY(0.0F);
        kaliButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaliButtonActionPerformed(evt);
            }
        });
        jPanel1.add(kaliButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, 100, 80));

        kurangButton.setBackground(new java.awt.Color(255, 153, 51));
        kurangButton.setFont(new java.awt.Font("JetBrains Mono", 0, 36)); // NOI18N
        kurangButton.setText("-");
        kurangButton.setAlignmentY(0.0F);
        kurangButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kurangButtonActionPerformed(evt);
            }
        });
        jPanel1.add(kurangButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 470, 100, 80));

        tambahButton.setBackground(new java.awt.Color(255, 153, 51));
        tambahButton.setFont(new java.awt.Font("JetBrains Mono", 0, 36)); // NOI18N
        tambahButton.setText("+");
        tambahButton.setAlignmentY(0.0F);
        tambahButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahButtonActionPerformed(evt);
            }
        });
        jPanel1.add(tambahButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 560, 100, 80));

        equalButton.setBackground(new java.awt.Color(255, 153, 51));
        equalButton.setFont(new java.awt.Font("JetBrains Mono", 0, 36)); // NOI18N
        equalButton.setText("=");
        equalButton.setAlignmentY(0.0F);
        equalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalButtonActionPerformed(evt);
            }
        });
        jPanel1.add(equalButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 650, 100, 80));

        toggleButton.setBackground(new java.awt.Color(255, 153, 51));
        toggleButton.setFont(new java.awt.Font("JetBrains Mono", 0, 36)); // NOI18N
        toggleButton.setText("+/-");
        toggleButton.setAlignmentY(0.0F);
        toggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleButtonActionPerformed(evt);
            }
        });
        jPanel1.add(toggleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 650, 100, 80));

        hapusButton.setBackground(new java.awt.Color(255, 153, 51));
        hapusButton.setFont(new java.awt.Font("JetBrains Mono", 0, 32)); // NOI18N
        hapusButton.setText("AC");
        hapusButton.setAlignmentY(0.0F);
        hapusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusButtonActionPerformed(evt);
            }
        });
        jPanel1.add(hapusButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 100, 80));

        sevenButton.setFont(new java.awt.Font("JetBrains Mono", 0, 36)); // NOI18N
        sevenButton.setText("7");
        sevenButton.setAlignmentY(0.0F);
        sevenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenButtonActionPerformed(evt);
            }
        });
        jPanel1.add(sevenButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 100, 80));

        eightButton.setFont(new java.awt.Font("JetBrains Mono", 0, 36)); // NOI18N
        eightButton.setText("8");
        eightButton.setAlignmentY(0.0F);
        eightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightButtonActionPerformed(evt);
            }
        });
        jPanel1.add(eightButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 100, 80));

        nineButton.setFont(new java.awt.Font("JetBrains Mono", 0, 36)); // NOI18N
        nineButton.setText("9");
        nineButton.setAlignmentY(0.0F);
        nineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineButtonActionPerformed(evt);
            }
        });
        jPanel1.add(nineButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, 100, 80));

        sixButton.setFont(new java.awt.Font("JetBrains Mono", 0, 36)); // NOI18N
        sixButton.setText("6");
        sixButton.setAlignmentY(0.0F);
        sixButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixButtonActionPerformed(evt);
            }
        });
        jPanel1.add(sixButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 470, 100, 80));

        fiveButton.setFont(new java.awt.Font("JetBrains Mono", 0, 36)); // NOI18N
        fiveButton.setText("5");
        fiveButton.setAlignmentY(0.0F);
        fiveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveButtonActionPerformed(evt);
            }
        });
        jPanel1.add(fiveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, 100, 80));

        fourButton.setFont(new java.awt.Font("JetBrains Mono", 0, 36)); // NOI18N
        fourButton.setText("4");
        fourButton.setAlignmentY(0.0F);
        fourButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourButtonActionPerformed(evt);
            }
        });
        jPanel1.add(fourButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, 100, 80));

        twoButton.setFont(new java.awt.Font("JetBrains Mono", 0, 36)); // NOI18N
        twoButton.setText("2");
        twoButton.setAlignmentY(0.0F);
        twoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoButtonActionPerformed(evt);
            }
        });
        jPanel1.add(twoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 560, 100, 80));

        threeButton.setFont(new java.awt.Font("JetBrains Mono", 0, 36)); // NOI18N
        threeButton.setText("3");
        threeButton.setAlignmentY(0.0F);
        threeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(threeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 560, 100, 80));

        oneButton.setFont(new java.awt.Font("JetBrains Mono", 0, 36)); // NOI18N
        oneButton.setMnemonic(1);
        oneButton.setText("1");
        oneButton.setAlignmentY(0.0F);
        oneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneButtonActionPerformed(evt);
            }
        });
        oneButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                oneButtonKeyPressed(evt);
            }
        });
        jPanel1.add(oneButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 560, 100, 80));

        zeroButton.setFont(new java.awt.Font("JetBrains Mono", 0, 36)); // NOI18N
        zeroButton.setText("0");
        zeroButton.setAlignmentY(0.0F);
        zeroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroButtonActionPerformed(evt);
            }
        });
        jPanel1.add(zeroButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 650, 200, 80));

        desimalButton.setFont(new java.awt.Font("JetBrains Mono", 0, 36)); // NOI18N
        desimalButton.setText(".");
        desimalButton.setAlignmentY(0.0F);
        desimalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desimalButtonActionPerformed(evt);
            }
        });
        jPanel1.add(desimalButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 650, 100, 80));

        faktorialButton.setFont(new java.awt.Font("JetBrains Mono", 0, 36)); // NOI18N
        faktorialButton.setText("x!");
        faktorialButton.setAlignmentY(0.0F);
        faktorialButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faktorialButtonActionPerformed(evt);
            }
        });
        jPanel1.add(faktorialButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 100, 47));

        expButton.setFont(new java.awt.Font("JetBrains Mono", 0, 36)); // NOI18N
        expButton.setText("Exp");
        expButton.setAlignmentY(0.0F);
        expButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expButtonActionPerformed(evt);
            }
        });
        jPanel1.add(expButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 100, 47));

        akarDuaButton.setFont(new java.awt.Font("JetBrains Mono", 0, 36)); // NOI18N
        akarDuaButton.setText("√");
        akarDuaButton.setAlignmentY(0.0F);
        akarDuaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akarDuaButtonActionPerformed(evt);
            }
        });
        jPanel1.add(akarDuaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 100, 80));

        delButton.setBackground(new java.awt.Color(255, 153, 51));
        delButton.setFont(new java.awt.Font("JetBrains Mono", 0, 32)); // NOI18N
        delButton.setText("del");
        delButton.setAlignmentY(0.0F);
        delButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delButtonActionPerformed(evt);
            }
        });
        jPanel1.add(delButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 100, 80));

        phiButton.setFont(new java.awt.Font("JetBrains Mono", 0, 36)); // NOI18N
        phiButton.setText("π");
        phiButton.setAlignmentY(0.0F);
        phiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phiButtonActionPerformed(evt);
            }
        });
        jPanel1.add(phiButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 100, 80));

        cosButton.setFont(new java.awt.Font("JetBrains Mono", 0, 36)); // NOI18N
        cosButton.setText("cos");
        cosButton.setAlignmentY(0.0F);
        cosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosButtonActionPerformed(evt);
            }
        });
        jPanel1.add(cosButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 100, 46));

        persenButton.setBackground(new java.awt.Color(255, 153, 51));
        persenButton.setFont(new java.awt.Font("JetBrains Mono", 0, 36)); // NOI18N
        persenButton.setText("%");
        persenButton.setAlignmentY(0.0F);
        persenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                persenButtonActionPerformed(evt);
            }
        });
        jPanel1.add(persenButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 100, 80));

        tanButton.setFont(new java.awt.Font("JetBrains Mono", 0, 36)); // NOI18N
        tanButton.setText("tan");
        tanButton.setAlignmentY(0.0F);
        tanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanButtonActionPerformed(evt);
            }
        });
        jPanel1.add(tanButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 100, 46));

        lnButton.setFont(new java.awt.Font("JetBrains Mono", 0, 36)); // NOI18N
        lnButton.setText("ln");
        lnButton.setAlignmentY(0.0F);
        lnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnButtonActionPerformed(evt);
            }
        });
        jPanel1.add(lnButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 100, 46));

        logButton.setFont(new java.awt.Font("JetBrains Mono", 0, 36)); // NOI18N
        logButton.setText("log");
        logButton.setAlignmentY(0.0F);
        logButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logButtonActionPerformed(evt);
            }
        });
        jPanel1.add(logButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 100, 80));

        squareButton.setFont(new java.awt.Font("JetBrains Mono", 0, 36)); // NOI18N
        squareButton.setText("x^2");
        squareButton.setAlignmentY(0.0F);
        squareButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                squareButtonActionPerformed(evt);
            }
        });
        jPanel1.add(squareButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 100, 40));

        reciprocalButton.setFont(new java.awt.Font("JetBrains Mono", 0, 36)); // NOI18N
        reciprocalButton.setText("1/x");
        reciprocalButton.setAlignmentY(0.0F);
        reciprocalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reciprocalButtonActionPerformed(evt);
            }
        });
        jPanel1.add(reciprocalButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 100, 40));

        powerButton.setFont(new java.awt.Font("JetBrains Mono", 0, 36)); // NOI18N
        powerButton.setText("x^y");
        powerButton.setAlignmentY(0.0F);
        powerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powerButtonActionPerformed(evt);
            }
        });
        jPanel1.add(powerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 100, 46));

        tanhButton.setFont(new java.awt.Font("JetBrains Mono", 1, 24)); // NOI18N
        tanhButton.setText("tanh");
        tanhButton.setAlignmentY(0.0F);
        tanhButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanhButtonActionPerformed(evt);
            }
        });
        jPanel1.add(tanhButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 100, 46));

        sinhButton.setFont(new java.awt.Font("JetBrains Mono", 1, 24)); // NOI18N
        sinhButton.setText("sinh");
        sinhButton.setAlignmentY(0.0F);
        sinhButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinhButtonActionPerformed(evt);
            }
        });
        jPanel1.add(sinhButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 100, 46));

        coshButton.setFont(new java.awt.Font("JetBrains Mono", 1, 24)); // NOI18N
        coshButton.setText("cosh");
        coshButton.setAlignmentY(0.0F);
        coshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coshButtonActionPerformed(evt);
            }
        });
        jPanel1.add(coshButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 100, 46));

        sinButton.setFont(new java.awt.Font("JetBrains Mono", 0, 36)); // NOI18N
        sinButton.setText("sin");
        sinButton.setAlignmentY(0.0F);
        sinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinButtonActionPerformed(evt);
            }
        });
        jPanel1.add(sinButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 100, 46));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateDisplay() {
        // Tampilkan histori di layar atas (hitam)
        expressionField.setText(calculator.getExpressionValue());
        // Tampilkan input/hasil di layar bawah (putih)
        displayTextField.setText(calculator.getDisplayValue());
    }    
    
    private void bagiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bagiButtonActionPerformed
        calculator.inputOperator("÷");
        updateDisplay();
        this.requestFocusInWindow();
    }//GEN-LAST:event_bagiButtonActionPerformed

    private void kaliButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaliButtonActionPerformed
        calculator.inputOperator("*");
        updateDisplay();
        this.requestFocusInWindow();
    }//GEN-LAST:event_kaliButtonActionPerformed

    private void kurangButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kurangButtonActionPerformed
        calculator.inputOperator("-");
        updateDisplay();
        this.requestFocusInWindow();
    }//GEN-LAST:event_kurangButtonActionPerformed

    private void tambahButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahButtonActionPerformed
        calculator.inputOperator("+");
        updateDisplay();
        this.requestFocusInWindow();
    }//GEN-LAST:event_tambahButtonActionPerformed

    private void equalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalButtonActionPerformed
        calculator.inputEquals();
        updateDisplay();
        this.requestFocusInWindow();
    }//GEN-LAST:event_equalButtonActionPerformed

    private void hapusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusButtonActionPerformed
        calculator.inputClear();
        updateDisplay();
        this.requestFocusInWindow();
    }//GEN-LAST:event_hapusButtonActionPerformed

    private void sevenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenButtonActionPerformed
        calculator.inputDigit("7");
        updateDisplay();
        this.requestFocusInWindow();
    }//GEN-LAST:event_sevenButtonActionPerformed

    private void eightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightButtonActionPerformed
        calculator.inputDigit("8");
        updateDisplay();
        this.requestFocusInWindow();
    }//GEN-LAST:event_eightButtonActionPerformed

    private void nineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineButtonActionPerformed
        calculator.inputDigit("9");
        updateDisplay();
        this.requestFocusInWindow();
    }//GEN-LAST:event_nineButtonActionPerformed

    private void sixButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixButtonActionPerformed
        calculator.inputDigit("6");
        updateDisplay();
        this.requestFocusInWindow();
    }//GEN-LAST:event_sixButtonActionPerformed

    private void fiveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveButtonActionPerformed
        calculator.inputDigit("5");
        updateDisplay();
        this.requestFocusInWindow();
    }//GEN-LAST:event_fiveButtonActionPerformed

    private void fourButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourButtonActionPerformed
        calculator.inputDigit("4");
        updateDisplay();
        this.requestFocusInWindow();
    }//GEN-LAST:event_fourButtonActionPerformed

    private void twoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoButtonActionPerformed
        calculator.inputDigit("2");
        updateDisplay();
        this.requestFocusInWindow();
    }//GEN-LAST:event_twoButtonActionPerformed

    private void threeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeButtonActionPerformed
        calculator.inputDigit("3");
        updateDisplay();
        this.requestFocusInWindow();
    }//GEN-LAST:event_threeButtonActionPerformed

    private void oneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneButtonActionPerformed
        calculator.inputDigit("1");
        updateDisplay();
        this.requestFocusInWindow();
    }//GEN-LAST:event_oneButtonActionPerformed

    private void zeroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroButtonActionPerformed
        calculator.inputDigit("0");
        updateDisplay();
        this.requestFocusInWindow();
    }//GEN-LAST:event_zeroButtonActionPerformed

    private void desimalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desimalButtonActionPerformed
        calculator.inputDecimal();
        updateDisplay();
        this.requestFocusInWindow();
    }//GEN-LAST:event_desimalButtonActionPerformed

    private void faktorialButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faktorialButtonActionPerformed
        calculator.inputUnaryOperation("x!");
        updateDisplay();
        this.requestFocusInWindow();
    }//GEN-LAST:event_faktorialButtonActionPerformed

    private void expButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expButtonActionPerformed
        calculator.inputOperator("Exp");
        updateDisplay();
        this.requestFocusInWindow();
    }//GEN-LAST:event_expButtonActionPerformed

    private void akarDuaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akarDuaButtonActionPerformed
        calculator.inputUnaryOperation("√");
        updateDisplay();
        this.requestFocusInWindow();
    }//GEN-LAST:event_akarDuaButtonActionPerformed

    private void delButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delButtonActionPerformed
        calculator.inputDelete();
        updateDisplay();
        this.requestFocusInWindow();
    }//GEN-LAST:event_delButtonActionPerformed

    private void phiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phiButtonActionPerformed
        calculator.inputConstant("π");
        updateDisplay();
        this.requestFocusInWindow();
    }//GEN-LAST:event_phiButtonActionPerformed

    private void cosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosButtonActionPerformed
        calculator.inputUnaryOperation("cos");
        updateDisplay();
        this.requestFocusInWindow();
    }//GEN-LAST:event_cosButtonActionPerformed

    private void persenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_persenButtonActionPerformed
        calculator.inputUnaryOperation("%");
        updateDisplay();
        this.requestFocusInWindow();
    }//GEN-LAST:event_persenButtonActionPerformed

    private void tanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanButtonActionPerformed
        calculator.inputUnaryOperation("tan");
        updateDisplay();
        this.requestFocusInWindow();
    }//GEN-LAST:event_tanButtonActionPerformed

    private void lnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnButtonActionPerformed
        calculator.inputUnaryOperation("ln");
        updateDisplay();
        this.requestFocusInWindow();
    }//GEN-LAST:event_lnButtonActionPerformed

    private void logButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logButtonActionPerformed
        calculator.inputUnaryOperation("log");
        updateDisplay();
        this.requestFocusInWindow();
    }//GEN-LAST:event_logButtonActionPerformed

    private void toggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleButtonActionPerformed
        calculator.inputToggleSign();
        updateDisplay();
        this.requestFocusInWindow();
    }//GEN-LAST:event_toggleButtonActionPerformed

    private void squareButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_squareButtonActionPerformed
        calculator.inputUnaryOperation("x^2");
        updateDisplay();
        this.requestFocusInWindow();
    }//GEN-LAST:event_squareButtonActionPerformed

    private void powerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powerButtonActionPerformed
        calculator.inputOperator("^");
        updateDisplay();
        this.requestFocusInWindow();
    }//GEN-LAST:event_powerButtonActionPerformed

    private void tanhButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanhButtonActionPerformed
        calculator.inputUnaryOperation("tanh");
        updateDisplay();
        this.requestFocusInWindow();
    }//GEN-LAST:event_tanhButtonActionPerformed

    private void sinhButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinhButtonActionPerformed
        calculator.inputUnaryOperation("sinh");
        updateDisplay();
        this.requestFocusInWindow();
    }//GEN-LAST:event_sinhButtonActionPerformed

    private void coshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coshButtonActionPerformed
        calculator.inputUnaryOperation("cosh");
        updateDisplay();
        this.requestFocusInWindow();
    }//GEN-LAST:event_coshButtonActionPerformed

    private void sinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinButtonActionPerformed
        calculator.inputUnaryOperation("sin");
        updateDisplay();
        this.requestFocusInWindow();
    }//GEN-LAST:event_sinButtonActionPerformed

    private void reciprocalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reciprocalButtonActionPerformed
        calculator.inputUnaryOperation("1/x");
        updateDisplay();
        this.requestFocusInWindow();
        
    }//GEN-LAST:event_reciprocalButtonActionPerformed

    private void displayTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_displayTextFieldActionPerformed

    private void expressionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expressionFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expressionFieldActionPerformed

    private void oneButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_oneButtonKeyPressed
        // TODO add your handling code here
    }//GEN-LAST:event_oneButtonKeyPressed

    private void jPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyPressed
    }//GEN-LAST:event_jPanel1KeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
    char key = evt.getKeyChar();

    // Cek untuk angka 0-9
    if (key >= '0' && key <= '9') {
        calculator.inputDigit(String.valueOf(key));
        updateDisplay();
    }

    // Cek untuk operator
    switch (key) {
        case '+':
            calculator.inputOperator("+");
            updateDisplay();
            break;
        case '-':
            calculator.inputOperator("-");
            updateDisplay();
            break;
        case '*':
            calculator.inputOperator("*");
            updateDisplay();
            break;
        case '/':
            calculator.inputOperator("/");
            updateDisplay();
            break;
        case '.':
            calculator.inputDecimal();
            updateDisplay();
            break;
    }

    // Cek untuk tombol non-karakter
    int keyCode = evt.getKeyCode();
    // ini untuk yang =, bisa pake enter
    if (keyCode == java.awt.event.KeyEvent.VK_ENTER) {
        calculator.inputEquals();
        updateDisplay();
    } else if (keyCode == java.awt.event.KeyEvent.VK_BACK_SPACE) {
        calculator.inputDelete(); // Tombol Del buat Delete satu per satu karakter
        updateDisplay();
        
    } else if (keyCode == java.awt.event.KeyEvent.VK_ESCAPE) {
        calculator.inputClear(); // Tombol ESC untuk 'AC'
        updateDisplay();
    }
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new KalkulatorFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton akarDuaButton;
    private javax.swing.JButton bagiButton;
    private javax.swing.JButton cosButton;
    private javax.swing.JButton coshButton;
    private javax.swing.JButton delButton;
    private javax.swing.JButton desimalButton;
    private javax.swing.JTextField displayTextField;
    private javax.swing.JButton eightButton;
    private javax.swing.JButton equalButton;
    private javax.swing.JButton expButton;
    private javax.swing.JTextField expressionField;
    private javax.swing.JButton faktorialButton;
    private javax.swing.JButton fiveButton;
    private javax.swing.JButton fourButton;
    private javax.swing.JButton hapusButton;
    private javax.swing.JPanel hasilPanel;
    private javax.swing.JPanel hasilPanel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel judulLabel;
    private javax.swing.JButton kaliButton;
    private javax.swing.JButton kurangButton;
    private javax.swing.JButton lnButton;
    private javax.swing.JButton logButton;
    private javax.swing.JButton nineButton;
    private javax.swing.JButton oneButton;
    private javax.swing.JButton persenButton;
    private javax.swing.JButton phiButton;
    private javax.swing.JButton powerButton;
    private javax.swing.JButton reciprocalButton;
    private javax.swing.JButton sevenButton;
    private javax.swing.JButton sinButton;
    private javax.swing.JButton sinhButton;
    private javax.swing.JButton sixButton;
    private javax.swing.JButton squareButton;
    private javax.swing.JButton tambahButton;
    private javax.swing.JButton tanButton;
    private javax.swing.JButton tanhButton;
    private javax.swing.JButton threeButton;
    private javax.swing.JButton toggleButton;
    private javax.swing.JButton twoButton;
    private javax.swing.JButton zeroButton;
    // End of variables declaration//GEN-END:variables
}
