/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pelabuhan_project;
import parking_logic.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Alesha Naila
 */
public class MainMenu extends javax.swing.JFrame {
    private KendaraanLinkedList listParkir;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainMenu.class.getName());

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        this.listParkir = new KendaraanLinkedList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnIKMasuk = new javax.swing.JButton();
        btnRiwayatParkir = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        btnOperasiDelete = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sistem Parkiran Pelabuhan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(41, 41, 41))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 23, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Main Menu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        btnIKMasuk.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnIKMasuk.setText("Input Kendaraan Masuk");
        btnIKMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIKMasukActionPerformed(evt);
            }
        });

        btnRiwayatParkir.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnRiwayatParkir.setText("Riwayat Parkir");
        btnRiwayatParkir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRiwayatParkirActionPerformed(evt);
            }
        });

        btnKeluar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        btnOperasiDelete.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnOperasiDelete.setText("Operasi Delete");
        btnOperasiDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOperasiDeleteActionPerformed(evt);
            }
        });

        btnSearch.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRiwayatParkir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIKMasuk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnOperasiDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnIKMasuk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRiwayatParkir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOperasiDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnKeluar)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 154, 344, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("© Andin 240048 Ale 240066 Faruq 240080");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 450, 328, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIKMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIKMasukActionPerformed
        InputMasuk formMasuk = new InputMasuk(this, this.listParkir); 
        formMasuk.setVisible(true);
        this.setVisible(false); 
    }//GEN-LAST:event_btnIKMasukActionPerformed

    private void btnRiwayatParkirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRiwayatParkirActionPerformed
        RiwayatParkir formRiwayat = new RiwayatParkir(this, this.listParkir);
        formRiwayat.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRiwayatParkirActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnOperasiDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOperasiDeleteActionPerformed
        OperasiDelete formDelete = new OperasiDelete(this, this.listParkir);
        formDelete.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnOperasiDeleteActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String noKendKey = JOptionPane.showInputDialog(this, "Masukkan No. Kendaraan yang dicari:");
        
        if (noKendKey == null || noKendKey.trim().isEmpty()) {
            return; // User membatalkan
        }

        Kendaraan kdr = listParkir.search(noKendKey.trim());
        
        if (kdr == null) {
            JOptionPane.showMessageDialog(this, "Data kendaraan " + noKendKey + " tidak ditemukan.", "Hasil Pencarian", JOptionPane.INFORMATION_MESSAGE);
        } else {
            // Kita bisa tampilkan di frame RiwayatParkir, tapi untuk simpel, kita tampilkan di message box
            long biaya = kdr.getBiayaParkir();
            String detail = String.format(
                "Data Ditemukan:\n" +
                "Nama: %s\n" +
                "No. Kendaraan: %s\n" +
                "Jenis: %s\n" +
                "Status: %s\n" +
                "Masuk: %s %s\n" +
                "Pulang: %s %s\n" +
                "Lama Hari: %d\n" +
                "Lama Jam: %s\n" +
                "Total Biaya: %,d",
                kdr.getPerson().getNama(),
                kdr.getNoKendaraan(),
                kdr.getJenisAsString(),
                kdr.getStatusAsString(),
                kdr.getWaktuDatang().getDate().toString(), kdr.getWaktuDatang().getTime().toString(),
                kdr.getWaktuPulang().getDate().toString(), kdr.getWaktuPulang().getTime().toString(),
                kdr.getLamaHari(),
                kdr.getLamaJam(),
                biaya
            );
            JOptionPane.showMessageDialog(this, detail, "Hasil Pencarian", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIKMasuk;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnOperasiDelete;
    private javax.swing.JButton btnRiwayatParkir;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
