/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pelabuhan_project;
import parking_logic.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author andin
 */
public class OperasiDelete extends javax.swing.JFrame {
    private KendaraanLinkedList listParkir;
    private JFrame parentMenu;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(OperasiDelete.class.getName());

    /**
     * Creates new form OperasiLinkedList
     */
        public OperasiDelete(JFrame parent, KendaraanLinkedList list) {
        initComponents();
        this.parentMenu = parent;
        this.listParkir = list;
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        panelDelete = new javax.swing.JPanel();
        btnDeleteAfter = new javax.swing.JButton();
        btnDeleteFirst = new javax.swing.JButton();
        btnDeleteLast = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setText("Operasi Delete");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(28, 28, 28))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        btnBack.setBackground(new java.awt.Color(255, 102, 102));
        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnBack.setText("X");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 40, -1));

        panelDelete.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Operasi Delete", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        btnDeleteAfter.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnDeleteAfter.setText("Delete After");
        btnDeleteAfter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAfterActionPerformed(evt);
            }
        });

        btnDeleteFirst.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnDeleteFirst.setText("Delete First");
        btnDeleteFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteFirstActionPerformed(evt);
            }
        });

        btnDeleteLast.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnDeleteLast.setText("Delete Last");
        btnDeleteLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteLastActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDeleteLayout = new javax.swing.GroupLayout(panelDelete);
        panelDelete.setLayout(panelDeleteLayout);
        panelDeleteLayout.setHorizontalGroup(
            panelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDeleteLayout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(panelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDeleteLast, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnDeleteAfter, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDeleteFirst, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(66, 66, 66))
        );
        panelDeleteLayout.setVerticalGroup(
            panelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDeleteLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnDeleteFirst)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDeleteAfter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDeleteLast)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        getContentPane().add(panelDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, 180));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.parentMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDeleteAfterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAfterActionPerformed
        String noKendKey = JOptionPane.showInputDialog(this, "Masukkan No. Kendaraan (data SETELAH ini akan dihapus):");

        if (noKendKey == null || noKendKey.trim().isEmpty()) {
            return; 
        }
        
        noKendKey = noKendKey.trim();

        try {
            if (listParkir.isEmpty()) {
                JOptionPane.showMessageDialog(this, "List parkir sudah kosong.", "Info", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            Node targetNode = listParkir.find(noKendKey);
            if (targetNode == null) {
                throw new DataNotFoundException("No. Kendaraan '" + noKendKey + "' tidak ditemukan.");
            }

            if (targetNode.next == null) {
                throw new DataNotFoundException("Tidak ada data setelah No. Kendaraan '" + noKendKey + "'.");
            }
            
            Kendaraan toDelete = targetNode.next.data;
            int pilihan = JOptionPane.showConfirmDialog(this,
                "Yakin ingin menghapus data " + toDelete.getNoKendaraan() + " (setelah " + noKendKey + ")?",
                "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);

            if (pilihan == JOptionPane.YES_OPTION) {
                Kendaraan deleted = listParkir.deleteAfter(noKendKey); 
                JOptionPane.showMessageDialog(this, "Berhasil menghapus: " + deleted.getNoKendaraan(), "Sukses", JOptionPane.INFORMATION_MESSAGE);
            }
            
        } catch (DataNotFoundException e) {
            JOptionPane.showMessageDialog(this, "Gagal menghapus: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteAfterActionPerformed

    private void btnDeleteFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteFirstActionPerformed
            try {
            if (listParkir.isEmpty()) {
                JOptionPane.showMessageDialog(this, "List parkir sudah kosong.", "Info", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            // Dapatkan data pertama untuk konfirmasi
            Kendaraan firstKendaraan = listParkir.getFirst().data;
            int pilihan = JOptionPane.showConfirmDialog(this,
                "Yakin ingin menghapus data pertama (" + firstKendaraan.getNoKendaraan() + ")?",
                "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);

            if (pilihan == JOptionPane.YES_OPTION) {
                Kendaraan deleted = listParkir.deleteFirst(); // Panggil logika deleteFirst
                JOptionPane.showMessageDialog(this, "Berhasil menghapus: " + deleted.getNoKendaraan(), "Sukses", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (DataNotFoundException e) {
            // Ini seharusnya tidak terjadi karena sudah dicek dgn isEmpty(), tapi untuk keamanan
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteFirstActionPerformed

    private void btnDeleteLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteLastActionPerformed
        try {
            if (listParkir.isEmpty()) {
                JOptionPane.showMessageDialog(this, "List parkir sudah kosong.", "Info", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            Kendaraan lastKendaraan = listParkir.getLast().data;
            int pilihan = JOptionPane.showConfirmDialog(this,
                "Yakin ingin menghapus data terakhir (" + lastKendaraan.getNoKendaraan() + ")?",
                "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);

            if (pilihan == JOptionPane.YES_OPTION) {
                Kendaraan deleted = listParkir.deleteLast(); 
                JOptionPane.showMessageDialog(this, "Berhasil menghapus: " + deleted.getNoKendaraan(), "Sukses", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (DataNotFoundException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteLastActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            // Buat objek DUMMY untuk testing
            JFrame dummyParent = new JFrame("Dummy Parent");
            KendaraanLinkedList dummyList = new KendaraanLinkedList();
            new OperasiDelete(dummyParent, dummyList).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteAfter;
    private javax.swing.JButton btnDeleteFirst;
    private javax.swing.JButton btnDeleteLast;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelDelete;
    // End of variables declaration//GEN-END:variables
}
