/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pelabuhan_project;

/**
 *
 * @author Alesha Naila
 */
import parking_logic.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
public class RiwayatParkir extends javax.swing.JFrame {
    
    private KendaraanLinkedList listParkir;
    private JFrame parentMenu;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RiwayatParkir.class.getName());
    
    
    private void tampilkanDataRiwayat() {
        // StringBuilder jauh lebih efisien untuk membangun string panjang
        StringBuilder sb = new StringBuilder();
        
        // 1. Buat Header Tabel
        sb.append("\t\t\t\t\tDaftar Kendaraan Parkir Pelabuhan\n");
        sb.append("=========================================================================================================================================\n");
        sb.append(String.format("%-4s %-15s %-12s %-11s %-10s %-12s %-12s %-10s %-10s %-10s %-10s %-12s\n",
            "No", "Nama Pemilik", "NoKend", "JenisKend", "Status", "TglDatang", "TglPulang", "JamDatang", "JamPulang", "Lama hari", "Lama Jam", "BiayaParkir"));
        sb.append("-----------------------------------------------------------------------------------------------------------------------------------------\n");
        
        long totalBiayaParkir = 0;

        if (listParkir.isEmpty()) {
            sb.append("|                                    TIDAK ADA DATA                                    |\n");
        } else {
            Node current = listParkir.getFirst();
            int i = 0;
            while (current != null) {
                Kendaraan kdr = current.data;
                long biaya = kdr.getBiayaParkir(); //
                totalBiayaParkir += biaya;
                
                // Ambil format string dari method formatUntukTabel() di Kendaraan.java
                sb.append(kdr.formatUntukTabel(i, biaya)); // method ini sudah punya \n di akhirnya
                
                current = current.next; //
                i++;
            }
        }

        sb.append("=========================================================================================================================================\n");
        sb.append(String.format("Total Biaya Parkir : %,d\n", totalBiayaParkir));
        
        // 6. Set teks ke JTextArea
        textAreaRiwayat.setText(sb.toString());
        // Set kursor ke atas
        textAreaRiwayat.setCaretPosition(0);
    }
    /**
     * Creates new form RiwayatParkir
     */
    public RiwayatParkir(JFrame parent, KendaraanLinkedList list) {
        initComponents();
        this.listParkir = list;
        this.parentMenu = parent;
        
        textAreaRiwayat.setFont(new java.awt.Font("Monospaced", java.awt.Font.PLAIN, 12));
        
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        
        tampilkanDataRiwayat();
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
    // Cukup panggil method yang sudah kita buat
    tampilkanDataRiwayat();
    JOptionPane.showMessageDialog(this, "Data riwayat berhasil diperbarui.", "Refresh Sukses", JOptionPane.INFORMATION_MESSAGE);
}
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaRiwayat = new javax.swing.JTextArea();
        btnBack = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setText("Riwayat Parkir");

        textAreaRiwayat.setColumns(20);
        textAreaRiwayat.setRows(5);
        jScrollPane1.setViewportView(textAreaRiwayat);

        btnBack.setBackground(new java.awt.Color(255, 102, 102));
        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnBack.setText("X");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton1.setText("Refresh");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1017, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(382, 382, 382)
                        .addComponent(jLabel1)))
                .addGap(0, 42, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnBack)
                .addGap(1, 1, 1)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.parentMenu.setVisible(true); // Tampilkan lagi MainMenu yang asli
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            // DIPERBAIKI: Untuk testing, kita buat list dummy DAN main menu dummy
            JFrame dummyFrame = new JFrame("Dummy Parent");
            KendaraanLinkedList dummyList = new KendaraanLinkedList();
            new RiwayatParkir(dummyFrame, dummyList).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textAreaRiwayat;
    // End of variables declaration//GEN-END:variables
}
